<?php
namespace Tests\Feature\Services;

use App\Services\LineBotPushService;
use function assertEquals;
use function dd;
use Tests\TestCase;

class LineBotServiceTest extends TestCase
{
    /** @var  LineBotPushService */
    private $lineBotService;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->lineBotService = app(LineBotPushService::class);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function PushMessage()
    {
        $this->markTestSkipped('OK!');
        $response = $this->lineBotService->pushMessage('果汁吃大便～揪咪');

        $this->assertEquals(200, $response->getHTTPStatus());
    }


    public function PushMessageWithObject()
    {
        $target = $this->lineBotService->buildTemplateMessageBuilder(
            'https://scontent.ftpe7-3.fna.fbcdn.net/v/t1.0-1/p200x200/28783736_874496826065433_2832967364813783040_n.jpg?oh=0650bd4499af50dd4e8fdd7340ff365d&oe=5B3F42CE',
            'https://www.facebook.com/pg/ChuCHandmade/about/?ref=page_internal',
            'Chu.C 啾囍'
        );

        $response = $this->lineBotService->pushMessage($target);

        dd($response);

        assertEquals(200, $response->getHTTPStatus());
    }

}
